import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/Public/Footer";
import { responsiveValues } from "@/utils/responsive";
import MobileFooter from "@/components/ui/Mobile/MobileFooter";

export const metadata: Metadata = {
   title: {
     default: 'بلاگ',
    template: 'بلاگ | %s',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = await responsiveValues()
  
  return (
    <html lang="fa" dir="rtl">
      <body>
        {children}
        {
          isMobile ? <MobileFooter /> : <Footer />
        }
        
      </body>
    </html>
  );
}
