import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/Public/Footer";



export const metadata: Metadata = {
   title: {
     default: 'بلاگ',
    template: 'بلاگ | %s',
  },
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
