import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
   title: {
     default: 'بلاگ',
    template: 'بلاگ | %s',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="fa" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  );
}
